import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, cpSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { createApp } from '../src/app.js';
import { hash } from '../src/store.js';
import { normalize } from '../src/adapters/espn.js';
import { weekly } from '../src/weekly.js';
import { html } from '../src/render.js';
function setup(t){const root=mkdtempSync(resolve(tmpdir(),'chatpdt-test-'));for(const d of ['knowledge','prompts'])cpSync(d,resolve(root,d),{recursive:true});const app=createApp(root,{MODEL_PROVIDER:'mock',WHATSAPP_ENABLED:'true',WHATSAPP_GROUP_ID:'league',LIVE_SEND:'false'});t.after(()=>app.store.close());return {...app,root};}
const fixture=()=>JSON.parse(readFileSync('fixtures/week.json'));
const proposal=()=>({submitter:'member-01',target:'members/member-01.md',category:'fact',proposedText:'# Approved demo fact\nA synthetic test fact.',source:{channel:'test',messageId:'m-1'}});
test('proposal cannot mutate memory until exact approval',t=>{const a=setup(t),before=hash(a.memory.documents());const s=a.memory.propose(proposal());assert.equal(hash(a.memory.documents()),before);assert.throws(()=>a.memory.decide(s.id,'approve','wrong'));a.memory.decide(s.id,'approve',hash(s));assert.match(readFileSync(a.memory.path(s.target),'utf8'),/synthetic/);assert.throws(()=>a.memory.decide(s.id,'approve',hash(s)));});
test('reject and stale base preserve canonical memory',t=>{const a=setup(t),s=a.memory.propose(proposal());a.memory.decide(s.id,'reject',hash(s));assert.equal(hash(readFileSync(a.memory.path(s.target),'utf8')),s.baseHash);const stale=a.memory.propose(proposal());writeFileSync(a.memory.path(stale.target),'# Newer approved content');assert.throws(()=>a.memory.decide(stale.id,'approve',hash(stale)),/Canonical memory changed/);});
test('path traversal and malformed proposals rejected',t=>{const a=setup(t);for(const target of ['../.env','members/../../.env','C:/secrets.md','editorial/not-there.md'])assert.throws(()=>a.memory.propose({...proposal(),target}));assert.throws(()=>a.memory.propose({...proposal(),category:'anything'}));});
test('retrieval excludes placeholders and conversations',async t=>{const a=setup(t);await a.agent.receive({id:'m',sender:'x',group:'league',text:'ChatPDT secret claim'});assert.ok(a.memory.retrieve('secret claim').every(d=>!d.path.startsWith('members/')));assert.equal(a.store.list('submission').length,0);});
test('wrong group, self, and uninvoked messages ignored; IDs deduplicated',async t=>{const a=setup(t),m={id:'id',sender:'x',group:'league',text:'ChatPDT hello'};for(const patch of [{group:'other'},{fromMe:true},{text:'hello'}])assert.equal((await a.agent.receive({...m,...patch})).ignored,true);assert.ok((await a.agent.receive(m)).text);assert.equal((await a.agent.receive(m)).duplicate,true);});
test('publishing requires approval and sends each channel once',async t=>{const a=setup(t),p=await a.publications.draft(fixture());await assert.rejects(()=>a.publications.publish(p.id),/approval/);a.publications.decide(p.id,'approve',a.publications.digest(p));await a.publications.publish(p.id);await a.publications.publish(p.id);assert.equal(a.store.db.prepare('SELECT count(*) AS n FROM deliveries').get().n,2);});
test('edits invalidate approval and PDF tampering is blocked',async t=>{const a=setup(t),p=await a.publications.draft(fixture());a.publications.decide(p.id,'approve',a.publications.digest(p));await a.publications.revise(p.id,{text:'Revised report',caption:'Fresh caption'});await assert.rejects(()=>a.publications.publish(p.id),/approval/);const edited=a.store.get(p.id);a.publications.decide(p.id,'approve',a.publications.digest(edited));writeFileSync(a.publications.artifacts(p).pdf,'tampered');await assert.rejects(()=>a.publications.publish(p.id),/PDF changed/);});
test('partial failure cannot resend successful channel or blindly retry unknown',async t=>{const a=setup(t);let gmail=0,whatsapp=0;a.publications.channels={gmail:{send:async()=>{gmail++;return {id:'sent'};}},whatsapp:{send:async()=>{whatsapp++;throw Error('timeout');}}};const p=await a.publications.draft(fixture());a.publications.decide(p.id,'approve',a.publications.digest(p));await assert.rejects(()=>a.publications.publish(p.id));await assert.rejects(()=>a.publications.publish(p.id),/reconciliation/);assert.equal(gmail,1);assert.equal(whatsapp,1);a.publications.reconcile(p.id+'-whatsapp','confirmed-sent','Provider message verified');await a.publications.publish(p.id);assert.equal(a.store.get(p.id).status,'published');assert.equal(whatsapp,1);});
test('changing destinations or mode invalidates approved package',async t=>{const a=setup(t),p=await a.publications.draft(fixture());a.publications.decide(p.id,'approve',a.publications.digest(p));const changed=a.store.get(p.id);changed.destinations.email='someone@example.invalid';a.store.put('publication',changed);await assert.rejects(()=>a.publications.publish(p.id),/approval/);});
test('weekly job is idempotent',async t=>{const a=setup(t);const one=await weekly(a,{},1,fixture()),two=await weekly(a,{},1,fixture());assert.equal(one.id,two.id);});
test('incomplete ESPN data is rejected, zero scores allowed',()=>{const raw={teams:[{id:1,name:'A'},{id:2,name:'B'}],schedule:[{id:1,matchupPeriodId:1,winner:'UNDECIDED',home:{teamId:1,totalPoints:0},away:{teamId:2,totalPoints:1}}]};assert.throws(()=>normalize(raw,{week:1}));raw.schedule[0].winner='AWAY';assert.equal(normalize(raw,{week:1}).matchups[0].home.score,0);delete raw.schedule[0].home.totalPoints;assert.throws(()=>normalize(raw,{week:1}),/Missing score/);});
test('HTML output escapes model and member content',()=>{const out=html('<script>x</script>','<img onerror=alert(1)>');assert.ok(!out.includes('<script>'));assert.ok(!out.includes('<img'));});
test('PDF contains valid header and EOF',async t=>{const a=setup(t),p=await a.publications.draft(fixture());const bytes=readFileSync(a.publications.artifacts(p).pdf);assert.equal(bytes.subarray(0,5).toString(),'%PDF-');assert.ok(bytes.toString().includes('%%EOF'));});
test('crash recovery completes already written approved memory',t=>{const a=setup(t),s=a.memory.propose(proposal());s.status='applying';s.resultHash=hash(s.proposedText);a.store.put('submission',s);writeFileSync(a.memory.path(s.target),s.proposedText);a.memory.recover();assert.equal(a.store.get(s.id).status,'approved');});



