import PDFDocument from 'pdfkit';
import { createWriteStream } from 'node:fs';

export const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paragraphs=value=>String(value||'').trim().split(/\r?\n\s*\r?\n/).map(p=>p.replace(/\s*\r?\n\s*/g,' ').replace(/\s+/g,' ').trim()).filter(Boolean);
const plain=value=>paragraphs(value).map(p=>p.replace(/\*/g,'')).join('\n\n');
const rich=value=>paragraphs(value).map(p=>`<p style="margin:0 0 15px">${escapeHTML(p).replace(/\*([^*]+)\*/g,'<em>$1</em>')}</p>`).join('');

export function html(title,text,visuals=null){
  const brand=visuals?.branding||{},editorial=visuals?.editorial||null;
  const logos=new Map((visuals?.teamLogos||[]).map(logo=>[logo.teamId,logo]));
  const stories=new Map((editorial?.matchupStories||[]).map(story=>[Number(story.id),story]));
  const header=brand.creightonHeader?'<div style="background:#fff"><img src="cid:chatpdt-creighton-header" alt="campus" style="display:block;width:100%;height:270px;object-fit:cover;object-position:center 54%;opacity:.78;border:0"></div>':'';
  const titleLogo=brand.chatpdtTitleLogo?'<div style="margin:-28px -28px 24px;padding:22px 28px 14px;background:linear-gradient(180deg,#edf4fb 0%,#ffffff 100%);border-top:4px solid #d8c9a7"><img src="cid:chatpdt-title-logo" alt="ChatPDT fantasy league agent" style="display:block;width:100%;max-width:640px;height:auto;object-fit:contain;margin:0 auto"></div>':'<p style="font:800 24px Arial,sans-serif;letter-spacing:2px;color:#1b3a63;margin:0 0 18px">CHATPDT</p>';
  const signatureLogo=brand.chatpdtSignatureLogo?'<img src="cid:chatpdt-signature-logo" alt="ChatPDT crest" style="display:block;width:150px;height:150px;object-fit:contain;margin-right:22px;flex:0 0 150px">':'';
  const teamRow=team=>{const item=logos.get(team.teamId);return `<tr><td width="54" valign="middle" style="width:54px;padding:8px 10px 8px 0">${item?`<img src="cid:${escapeHTML(item.cid)}" alt="" width="42" height="42" style="display:block;width:42px;height:42px;object-fit:contain;border:0">`:''}</td><td valign="middle" style="padding:8px 12px 8px 0;font:700 15px/1.25 Arial,sans-serif;color:#182b3b">${escapeHTML(team.name)}</td><td width="92" valign="middle" align="right" style="width:92px;padding:8px 0;text-align:right;white-space:nowrap;font:700 21px/1 Arial,sans-serif;color:#1b3a63">${Number(team.score).toFixed(2)}</td></tr>`;};
  const scoreboard=(visuals?.scoreboard||[]).map(game=>{const story=stories.get(Number(game.id));return `<article style="margin:0 0 22px;border:1px solid #d8c9a7;border-radius:11px;overflow:hidden;background:#fff"><div style="height:6px;background:#1b3a63"></div><div style="padding:14px 18px;background:#f4f7f9"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:collapse"><tbody>${teamRow(game.away)}<tr><td colspan="3" style="height:1px;padding:0;border-top:1px solid #dce3e8;font-size:0;line-height:0">&nbsp;</td></tr>${teamRow(game.home)}</tbody></table></div>${story?`<div style="padding:18px 20px 7px"><p style="margin:0 0 12px;font:700 12px/1.4 Arial,sans-serif;letter-spacing:.5px;text-transform:uppercase;color:#6b7280">${escapeHTML(story.managerLine||'')}</p>${rich(story.text)}</div>`:''}</article>`;}).join('');
  const standings=(visuals?.standings||[]).map((team,index)=>{const item=logos.get(team.teamId);return `<tr><td style="padding:7px;border-bottom:1px solid #e5e7eb">${index+1}</td><td style="padding:7px;border-bottom:1px solid #e5e7eb"><span style="display:flex;align-items:center;gap:8px">${item?`<img src="cid:${escapeHTML(item.cid)}" alt="" style="width:28px;height:28px;object-fit:contain">`:''}${escapeHTML(team.name)}</span></td><td style="padding:7px;text-align:center;border-bottom:1px solid #e5e7eb">${team.wins??'—'}-${team.losses??'—'}</td><td style="padding:7px;text-align:right;border-bottom:1px solid #e5e7eb">${team.pointsFor==null?'—':Number(team.pointsFor).toFixed(2)}</td></tr>`;}).join('');
  const awards=(visuals?.awards||[]).map(award=>`<section style="margin:20px 0;padding:18px;border:1px solid #d8c9a7;border-radius:10px;background:#fbf8f1"><h3 style="margin:0 0 14px;color:#1b3a63">${escapeHTML(award.label)}</h3>${award.recipients.map(recipient=>{const item=logos.get(recipient.teamId);const photoCells=recipient.photos.map((photo,index)=>`<td width="50%" valign="top" style="width:50%;vertical-align:top;${index===0?'padding:0 8px 0 0':'padding:0 0 0 8px'}"><img src="cid:${escapeHTML(photo.cid)}" alt="Archive photo of ${escapeHTML(recipient.manager)}" width="300" style="display:block;width:100%;height:235px;object-fit:cover;border:0;border-radius:8px">${photo.caption||photo.approximateYear?`<p style="margin:8px 2px 0;font:12px/1.45 Arial,sans-serif;color:#526678">${escapeHTML([photo.caption,photo.approximateYear].filter(Boolean).join(' · '))}</p>`:''}</td>`).join('');return `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:collapse;margin:0 0 16px"><tbody><tr>${item?`<td width="54" valign="middle" style="width:54px;padding:0 12px 0 0"><img src="cid:${escapeHTML(item.cid)}" alt="" width="46" height="46" style="display:block;width:46px;height:46px;object-fit:contain;border:0"></td>`:''}<td valign="middle" style="padding:0;font:15px/1.45 Arial,sans-serif;color:#182b3b"><strong>${escapeHTML(recipient.manager)}</strong><br>${escapeHTML(recipient.team)} · ${Number(recipient.score).toFixed(2)} points</td></tr></tbody></table>${recipient.photos.length?`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;table-layout:fixed;border-collapse:separate"><tbody><tr>${photoCells}</tr></tbody></table>`:'<p style="font:13px Arial,sans-serif;color:#6b7280">Archive photos have not been added for this member yet.</p>'}`;}).join('')}</section>`).join('');
  const awardsSection=awards?`<hr style="margin:32px 0;border:0;border-top:2px solid #d8c9a7"><h2 style="color:#1b3a63">${escapeHTML(visuals.title||'Phi & Maloney of the Week')}</h2>${awards}`:'';
  const powerRankings=(editorial?.powerRankings||[]).map(entry=>{const item=logos.get(entry.teamId);const heading=entry.heading||`${entry.rank}. ${entry.team} — ${entry.manager}`;const commentary=entry.commentary||[entry.history,entry.roast].filter(Boolean).join(' ');return `<article style="margin:0 0 18px;border:1px solid #cbd8e6;border-left:6px solid #1b3a63;border-radius:9px;overflow:hidden;background:#f7f9fb"><div style="padding:15px 17px 11px;background:#edf3f8"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:collapse"><tbody><tr>${item?`<td width="64" valign="middle" style="width:64px;padding:0 16px 0 0"><img src="cid:${escapeHTML(item.cid)}" alt="" width="48" height="48" style="display:block;width:48px;height:48px;object-fit:contain;border:0"></td>`:'<td width="0" style="width:0;padding:0"></td>'}<td valign="middle" style="padding:0"><p style="margin:0 0 2px;font:800 17px/1.3 Arial,sans-serif;color:#1b3a63">${escapeHTML(heading)}</p>${entry.record?`<p style="margin:0;font:12px/1.4 Arial,sans-serif;color:#526678">Record <strong>${escapeHTML(entry.record)}</strong> · Week 2 <strong>${Number(entry.weekScore).toFixed(2)}</strong> · Season PF <strong>${Number(entry.pointsFor).toFixed(2)}</strong> · Acquisitions <strong>${entry.moves}</strong></p>`:''}</td></tr></tbody></table></div><div style="padding:14px 17px 16px">${entry.topWeek?`<p style="margin:0 0 7px;font:13px/1.45 Arial,sans-serif;color:#182b3b"><strong>Week 2 leaders:</strong> ${escapeHTML(entry.topWeek)}</p>`:''}${entry.topSeason?`<p style="margin:0 0 7px;font:13px/1.45 Arial,sans-serif;color:#182b3b"><strong>2026 leaders:</strong> ${escapeHTML(entry.topSeason)}</p>`:''}${entry.topBench?`<p style="margin:0 0 12px;font:13px/1.45 Arial,sans-serif;color:#526678"><strong>Bench watch:</strong> ${escapeHTML(entry.topBench)}</p>`:''}<p style="margin:0;font:15px/1.62 Georgia,serif;color:#182b3b">${escapeHTML(commentary)}</p></div></article>`;}).join('');
  const mainCopy=editorial?`${rich(editorial.introText)}${scoreboard?`<h2 style="margin:30px 0 16px;color:#1b3a63;font:700 23px Georgia,serif">Week 2 Matchups</h2>${scoreboard}`:''}${awardsSection}${powerRankings?`<h2 style="margin:34px 0 16px;color:#1b3a63;font:700 23px Georgia,serif">ChatPDT Power Rankings: Week 2</h2>${powerRankings}`:''}${rich(editorial.postMatchupsText)}`:`${scoreboard?`<section style="margin:24px 0;padding:18px;background:#f4f7f9;border-radius:10px"><h2 style="margin-top:0;color:#1b3a63">ESPN Matchup Board</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:10px">${scoreboard}</div></section>`:''}${rich(text)}`;
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHTML(title)}</title></head><body style="margin:0;padding:12px;background:#eef2f5"><main style="font:16px/1.62 Georgia,serif;color:#182b3b;max-width:720px;margin:12px auto;background:white;border-radius:10px;overflow:hidden;box-shadow:0 4px 18px rgba(24,43,59,.12)">${header}<div style="padding:28px">${titleLogo}<h1 style="font-size:32px;line-height:1.15;margin:10px 0 22px;color:#182b3b">${escapeHTML(title)}</h1>${mainCopy}${standings&&!editorial?.combineStandingsWithPowerRankings?`<hr style="margin:32px 0;border:0;border-top:2px solid #d8c9a7"><h2 style="color:#1b3a63">League Table</h2><table style="width:100%;border-collapse:collapse;font:14px Arial,sans-serif"><thead><tr><th style="text-align:left;padding:7px">#</th><th style="text-align:left;padding:7px">Team</th><th style="padding:7px">Record</th><th style="text-align:right;padding:7px">PF</th></tr></thead><tbody>${standings}</tbody></table>`:''}${awards&&!editorial?awardsSection:''}<div style="display:flex;align-items:center;flex-wrap:wrap;margin:38px 0 12px;padding:22px;border:2px solid #1b3a63;border-radius:12px;background:#edf4ff;box-shadow:0 3px 10px rgba(27,58,99,.12)">${signatureLogo}<div style="flex:1;min-width:260px"><p style="margin:0 0 2px;font:800 25px/1.15 Arial,sans-serif;color:#1b3a63">ChatPDT</p><p style="margin:0 0 12px;font:700 14px/1.35 Arial,sans-serif;letter-spacing:.6px;text-transform:uppercase;color:#526678">League Parliamentarian</p><p style="margin:0 0 8px;font:italic 15px/1.5 Georgia,serif;color:#182b3b">Still reviewing the minutes from last week.</p><p style="margin:0;font:700 12px Arial,sans-serif;color:#1b3a63">Trust the process.</p></div></div><p style="font:11px Arial,sans-serif;color:#6b7280">Prepared for league review. Source records and approved visual hashes are retained with this edition.</p></div></main></body></html>`;
}

function writeMatchup(doc,game,story,teamLogos){
  if(doc.y>585)doc.addPage();
  const x=54,y=doc.y,w=504;
  doc.roundedRect(x,y,w,78,7).fillAndStroke('#f4f7f9','#d8c9a7');
  [game.away,game.home].forEach((team,side)=>{const lineY=y+8+side*32,item=teamLogos.get(team.teamId);if(item)doc.image(item.path,x+10,lineY,{fit:[25,25]});doc.fillColor('#182b3b').font('Helvetica-Bold').fontSize(10).text(team.name,x+44,lineY+7,{width:355,ellipsis:true});doc.fillColor('#1b3a63').fontSize(13).text(Number(team.score).toFixed(2),x+420,lineY+5,{width:70,align:'right'});});
  doc.x=54;doc.y=y+92;
  if(story?.managerLine)doc.fillColor('#6b7280').font('Helvetica-Bold').fontSize(8.5).text(plain(story.managerLine).toUpperCase(),{characterSpacing:.35});
  if(story?.text){doc.moveDown(.55);doc.fillColor('#182b3b').font('Helvetica').fontSize(10.3).text(plain(story.text),{lineGap:4});}
  doc.moveDown(1.15);
}

function writeAwards(doc,visuals){
  if(!visuals?.awards?.length)return;
  doc.addPage();doc.fillColor('#182b3b').font('Helvetica-Bold').fontSize(23).text(visuals.title||'Phi & Maloney of the Week');doc.moveDown();
  for(const award of visuals.awards){for(const recipient of award.recipients){if(doc.y>600)doc.addPage();doc.fillColor('#1b3a63').font('Helvetica-Bold').fontSize(17).text(award.label);doc.fillColor('#182b3b').font('Helvetica').fontSize(11).text(`${recipient.manager} · ${recipient.team} · ${Number(recipient.score).toFixed(2)} points`);doc.moveDown(.5);if(recipient.photos.length){const imageY=doc.y,gutter=16,columnWidth=244;recipient.photos.forEach((photo,index)=>doc.image(photo.path,54+index*(columnWidth+gutter),imageY,{cover:[columnWidth,170],align:'center',valign:'center'}));const captionY=imageY+178;recipient.photos.forEach((photo,index)=>{if(photo.caption||photo.approximateYear)doc.fillColor('#526678').font('Helvetica').fontSize(8).text([photo.caption,photo.approximateYear].filter(Boolean).join(' · '),54+index*(columnWidth+gutter),captionY,{width:columnWidth,lineGap:2});});doc.x=54;doc.y=captionY+46;}else doc.fillColor('#526678').font('Helvetica-Oblique').fontSize(10).text('Archive photos have not been added for this member yet.');doc.moveDown();}}
}

export async function pdf(path,title,text,visuals=null){
  const doc=new PDFDocument({size:'LETTER',margins:{top:54,bottom:54,left:54,right:54},bufferPages:true,info:{Title:title,Author:'ChatPDT'}});
  const stream=createWriteStream(path);const done=new Promise((resolve,reject)=>{stream.on('finish',resolve);stream.on('error',reject);doc.on('error',reject);});doc.pipe(stream);
  if(visuals?.branding?.creightonHeader){doc.save().rect(54,54,504,180).clip().image(visuals.branding.creightonHeader.path,54,54,{cover:[504,180],align:'center',valign:'center'}).restore();doc.x=54;doc.y=244;}
  if(visuals?.branding?.chatpdtTitleLogo){const y=doc.y;doc.image(visuals.branding.chatpdtTitleLogo.path,54,y,{fit:[390,100],align:'left',valign:'center'});doc.x=54;doc.y=y+108;}
  else doc.fillColor('#1b3a63').font('Helvetica-Bold').fontSize(16).text('CHATPDT');
  doc.moveDown().fillColor('#182b3b').font('Helvetica-Bold').fontSize(25).text(title);
  const teamLogos=new Map((visuals?.teamLogos||[]).map(logo=>[logo.teamId,logo])),editorial=visuals?.editorial||null;
  if(editorial){
    doc.moveDown().fillColor('#182b3b').font('Helvetica').fontSize(10.5).text(plain(editorial.introText),{lineGap:4});
    doc.moveDown(1.2).fillColor('#1b3a63').font('Helvetica-Bold').fontSize(18).text('Week 2 Matchups');doc.moveDown(.7);
    const stories=new Map((editorial.matchupStories||[]).map(story=>[Number(story.id),story]));
    for(const game of visuals?.scoreboard||[])writeMatchup(doc,game,stories.get(Number(game.id)),teamLogos);
    writeAwards(doc,visuals);
    if(editorial.powerRankings?.length){if(doc.y>600)doc.addPage();doc.fillColor('#1b3a63').font('Helvetica-Bold').fontSize(18).text('ChatPDT Power Rankings: Week 2');doc.moveDown(.7);for(const entry of editorial.powerRankings){if(doc.y>535)doc.addPage();const y=doc.y,heading=entry.heading||`${entry.rank}. ${entry.team} — ${entry.manager}`,commentary=entry.commentary||[entry.history,entry.roast].filter(Boolean).join(' ');doc.rect(54,y,5,70).fill('#1b3a63');doc.fillColor('#1b3a63').font('Helvetica-Bold').fontSize(10).text(heading,70,y,{width:475});doc.moveDown(.25);if(entry.record)doc.fillColor('#526678').font('Helvetica').fontSize(8.5).text(`Record ${entry.record} · Week 2 ${Number(entry.weekScore).toFixed(2)} · PF ${Number(entry.pointsFor).toFixed(2)} · Acquisitions ${entry.moves}`,{width:475});doc.moveDown(.25);if(entry.topWeek)doc.fillColor('#182b3b').fontSize(8.5).text(`Week 2 leaders: ${entry.topWeek}`,{width:475});if(entry.topSeason)doc.text(`2026 leaders: ${entry.topSeason}`,{width:475});doc.moveDown(.25);doc.fillColor('#182b3b').font('Helvetica').fontSize(9).text(commentary,{width:475,lineGap:2});doc.moveDown(.9);}}
    if(editorial.postMatchupsText){if(doc.y>620)doc.addPage();doc.fillColor('#182b3b').font('Helvetica').fontSize(10.5).text(plain(editorial.postMatchupsText),{lineGap:4});}
  }else{
    if(visuals?.scoreboard?.length){doc.moveDown().fillColor('#1b3a63').font('Helvetica-Bold').fontSize(17).text('ESPN Matchup Board');const startY=doc.y+8;visuals.scoreboard.forEach((game,index)=>{const col=index%2,row=Math.floor(index/2),x=54+col*255,y=startY+row*92;doc.roundedRect(x,y,244,82,7).fillAndStroke('#f4f7f9','#dce3e8');[game.away,game.home].forEach((team,side)=>{const lineY=y+8+side*35,item=teamLogos.get(team.teamId);if(item)doc.image(item.path,x+8,lineY,{fit:[28,28]});doc.fillColor('#182b3b').font('Helvetica').fontSize(9).text(team.name,x+42,lineY+9,{width:145,ellipsis:true});doc.font('Helvetica-Bold').fontSize(12).text(Number(team.score).toFixed(2),x+190,lineY+7,{width:44,align:'right'});});});doc.y=startY+Math.ceil(visuals.scoreboard.length/2)*92;doc.addPage();}
    doc.fillColor('#182b3b').font('Helvetica').fontSize(11).text(text,{lineGap:5});
  }
  if(visuals?.standings?.length&&!editorial?.combineStandingsWithPowerRankings){if(doc.y>390)doc.addPage();else doc.moveDown(2);doc.fillColor('#182b3b').font('Helvetica-Bold').fontSize(23).text('League Table');doc.moveDown();visuals.standings.forEach((team,index)=>{const y=doc.y,item=teamLogos.get(team.teamId);if(item)doc.image(item.path,54,y,{fit:[24,24]});doc.fillColor('#182b3b').font('Helvetica').fontSize(10).text(`${index+1}. ${team.name}`,86,y+6,{width:280});doc.text(`${team.wins??'—'}-${team.losses??'—'}`,380,y+6,{width:55,align:'center'});doc.text(team.pointsFor==null?'—':Number(team.pointsFor).toFixed(2),455,y+6,{width:90,align:'right'});doc.y=y+32;});}
  if(!editorial)writeAwards(doc,visuals);
  const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(i);doc.fontSize(9).fillColor('#526678').text(`${i+1} / ${range.count}`,54,750,{lineBreak:false});}
  doc.end();await done;
}



